//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 10:05:12 PM CET 
//


package ftn.xscience.model.coverletter;


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ftn.xscience.model.publication.TList;
import ftn.xscience.model.publication.TStyle;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_xscience_com.data.coverletter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TCLSectionList_QNAME = new QName("https://www.xscience.com/data/coverLetter.xsd", "List");
    private final static QName _TCLSectionStyle_QNAME = new QName("https://www.xscience.com/data/coverLetter.xsd", "Style");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_xscience_com.data.coverletter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoverLetter }
     * 
     */
    public CoverLetter createCoverLetter() {
        return new CoverLetter();
    }

    /**
     * Create an instance of {@link CoverLetter.Content }
     * 
     */
    public CoverLetter.Content createCoverLetterContent() {
        return new CoverLetter.Content();
    }

    /**
     * Create an instance of {@link TCLSection }
     * 
     */
    public TCLSection createTCLSection() {
        return new TCLSection();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/coverLetter.xsd", name = "List", scope = TCLSection.class)
    public JAXBElement<TList> createTCLSectionList(TList value) {
        return new JAXBElement<TList>(_TCLSectionList_QNAME, TList.class, TCLSection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/coverLetter.xsd", name = "Style", scope = TCLSection.class)
    public JAXBElement<TStyle> createTCLSectionStyle(TStyle value) {
        return new JAXBElement<TStyle>(_TCLSectionStyle_QNAME, TStyle.class, TCLSection.class, value);
    }

}
