//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.01 at 11:31:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.xscience.com/data/coverLetter.xsd", 
					xmlns = {
							@javax.xml.bind.annotation.XmlNs(namespaceURI = "https://www.xscience.com/data/coverLetter.xsd", prefix = ""),
							@javax.xml.bind.annotation.XmlNs(namespaceURI = "https://www.xscience.com/data/publication.xsd", prefix = "pbl")
					},elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)package ftn.xscience.model.coverletter;
