//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 10:05:30 PM CET 
//


package ftn.xscience.model.review;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ftn.xscience.model.publication.TList;
import ftn.xscience.model.publication.TStyle;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_xscience_com.data.review package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TCommentForEditorList_QNAME = new QName("https://www.xscience.com/data/review.xsd", "List");
    private final static QName _TCommentForEditorStyle_QNAME = new QName("https://www.xscience.com/data/review.xsd", "Style");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_xscience_com.data.review
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link Review.Content }
     * 
     */
    public Review.Content createReviewContent() {
        return new Review.Content();
    }

    /**
     * Create an instance of {@link TCommentForEditor }
     * 
     */
    public TCommentForEditor createTCommentForEditor() {
        return new TCommentForEditor();
    }

    /**
     * Create an instance of {@link TEditSuggestion }
     * 
     */
    public TEditSuggestion createTEditSuggestion() {
        return new TEditSuggestion();
    }

    /**
     * Create an instance of {@link Review.Content.Evaluation }
     * 
     */
    public Review.Content.Evaluation createReviewContentEvaluation() {
        return new Review.Content.Evaluation();
    }

    /**
     * Create an instance of {@link Review.Content.CommentForAuthor }
     * 
     */
    public Review.Content.CommentForAuthor createReviewContentCommentForAuthor() {
        return new Review.Content.CommentForAuthor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/review.xsd", name = "List", scope = TCommentForEditor.class)
    public JAXBElement<TList> createTCommentForEditorList(TList value) {
        return new JAXBElement<TList>(_TCommentForEditorList_QNAME, TList.class, TCommentForEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/review.xsd", name = "Style", scope = TCommentForEditor.class)
    public JAXBElement<TStyle> createTCommentForEditorStyle(TStyle value) {
        return new JAXBElement<TStyle>(_TCommentForEditorStyle_QNAME, TStyle.class, TCommentForEditor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/review.xsd", name = "List", scope = TEditSuggestion.class)
    public JAXBElement<TList> createTEditSuggestionList(TList value) {
        return new JAXBElement<TList>(_TCommentForEditorList_QNAME, TList.class, TEditSuggestion.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/review.xsd", name = "Style", scope = TEditSuggestion.class)
    public JAXBElement<TStyle> createTEditSuggestionStyle(TStyle value) {
        return new JAXBElement<TStyle>(_TCommentForEditorStyle_QNAME, TStyle.class, TEditSuggestion.class, value);
    }

}
