//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 10:05:30 PM CET 
//


package ftn.xscience.model.review;


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import ftn.xscience.model.publication.TAuthorInformation;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Content">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Reviewer" type="{https://www.xscience.com/data/publication.xsd}TAuthorInformation"/>
 *                   &lt;element name="Evaluation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Originality" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
 *                             &lt;element name="AdequateLiterature" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
 *                             &lt;element name="Methodology" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
 *                             &lt;element name="Inference" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
 *                             &lt;element name="Readability" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RecommendationForEditor">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="ACCEPT"/>
 *                         &lt;enumeration value="MINOR REVISION"/>
 *                         &lt;enumeration value="MAJOR REVISION"/>
 *                         &lt;enumeration value="REJECT"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CommentForEditor" type="{https://www.xscience.com/data/review.xsd}TCommentForEditor" minOccurs="0"/>
 *                   &lt;element name="CommentForAuthor" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EditSuggestion" type="{https://www.xscience.com/data/review.xsd}TEditSuggestion" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Review")
public class Review {

    @XmlElement(name = "Content", required = true)
    protected Review.Content content;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Content }
     *     
     */
    public Review.Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Content }
     *     
     */
    public void setContent(Review.Content value) {
        this.content = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Reviewer" type="{https://www.xscience.com/data/publication.xsd}TAuthorInformation"/>
     *         &lt;element name="Evaluation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Originality" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
     *                   &lt;element name="AdequateLiterature" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
     *                   &lt;element name="Methodology" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
     *                   &lt;element name="Inference" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
     *                   &lt;element name="Readability" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RecommendationForEditor">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="ACCEPT"/>
     *               &lt;enumeration value="MINOR REVISION"/>
     *               &lt;enumeration value="MAJOR REVISION"/>
     *               &lt;enumeration value="REJECT"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CommentForEditor" type="{https://www.xscience.com/data/review.xsd}TCommentForEditor" minOccurs="0"/>
     *         &lt;element name="CommentForAuthor" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EditSuggestion" type="{https://www.xscience.com/data/review.xsd}TEditSuggestion" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reviewer",
        "evaluation",
        "recommendationForEditor",
        "commentForEditor",
        "commentForAuthor"
    })
    public static class Content {

        @XmlElement(name = "Reviewer", required = true)
        protected TAuthorInformation reviewer;
        @XmlElement(name = "Evaluation", required = true)
        protected Review.Content.Evaluation evaluation;
        @XmlElement(name = "RecommendationForEditor", required = true)
        protected String recommendationForEditor;
        @XmlElement(name = "CommentForEditor")
        protected TCommentForEditor commentForEditor;
        @XmlElement(name = "CommentForAuthor")
        protected Review.Content.CommentForAuthor commentForAuthor;

        /**
         * Gets the value of the reviewer property.
         * 
         * @return
         *     possible object is
         *     {@link TAuthorInformation }
         *     
         */
        public TAuthorInformation getReviewer() {
            return reviewer;
        }

        /**
         * Sets the value of the reviewer property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAuthorInformation }
         *     
         */
        public void setReviewer(TAuthorInformation value) {
            this.reviewer = value;
        }

        /**
         * Gets the value of the evaluation property.
         * 
         * @return
         *     possible object is
         *     {@link Review.Content.Evaluation }
         *     
         */
        public Review.Content.Evaluation getEvaluation() {
            return evaluation;
        }

        /**
         * Sets the value of the evaluation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Review.Content.Evaluation }
         *     
         */
        public void setEvaluation(Review.Content.Evaluation value) {
            this.evaluation = value;
        }

        /**
         * Gets the value of the recommendationForEditor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecommendationForEditor() {
            return recommendationForEditor;
        }

        /**
         * Sets the value of the recommendationForEditor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecommendationForEditor(String value) {
            this.recommendationForEditor = value;
        }

        /**
         * Gets the value of the commentForEditor property.
         * 
         * @return
         *     possible object is
         *     {@link TCommentForEditor }
         *     
         */
        public TCommentForEditor getCommentForEditor() {
            return commentForEditor;
        }

        /**
         * Sets the value of the commentForEditor property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCommentForEditor }
         *     
         */
        public void setCommentForEditor(TCommentForEditor value) {
            this.commentForEditor = value;
        }

        /**
         * Gets the value of the commentForAuthor property.
         * 
         * @return
         *     possible object is
         *     {@link Review.Content.CommentForAuthor }
         *     
         */
        public Review.Content.CommentForAuthor getCommentForAuthor() {
            return commentForAuthor;
        }

        /**
         * Sets the value of the commentForAuthor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Review.Content.CommentForAuthor }
         *     
         */
        public void setCommentForAuthor(Review.Content.CommentForAuthor value) {
            this.commentForAuthor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EditSuggestion" type="{https://www.xscience.com/data/review.xsd}TEditSuggestion" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "editSuggestion"
        })
        public static class CommentForAuthor {

            @XmlElement(name = "EditSuggestion")
            protected List<TEditSuggestion> editSuggestion;

            /**
             * Gets the value of the editSuggestion property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the editSuggestion property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEditSuggestion().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TEditSuggestion }
             * 
             * 
             */
            public List<TEditSuggestion> getEditSuggestion() {
                if (editSuggestion == null) {
                    editSuggestion = new ArrayList<TEditSuggestion>();
                }
                return this.editSuggestion;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Originality" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
         *         &lt;element name="AdequateLiterature" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
         *         &lt;element name="Methodology" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
         *         &lt;element name="Inference" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
         *         &lt;element name="Readability" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "originality",
            "adequateLiterature",
            "methodology",
            "inference",
            "readability"
        })
        public static class Evaluation {

            @XmlElement(name = "Originality", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation originality;
            @XmlElement(name = "AdequateLiterature", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation adequateLiterature;
            @XmlElement(name = "Methodology", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation methodology;
            @XmlElement(name = "Inference", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation inference;
            @XmlElement(name = "Readability", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation readability;

            /**
             * Gets the value of the originality property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getOriginality() {
                return originality;
            }

            /**
             * Sets the value of the originality property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setOriginality(TRevisionEvaluation value) {
                this.originality = value;
            }

            /**
             * Gets the value of the adequateLiterature property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getAdequateLiterature() {
                return adequateLiterature;
            }

            /**
             * Sets the value of the adequateLiterature property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setAdequateLiterature(TRevisionEvaluation value) {
                this.adequateLiterature = value;
            }

            /**
             * Gets the value of the methodology property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getMethodology() {
                return methodology;
            }

            /**
             * Sets the value of the methodology property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setMethodology(TRevisionEvaluation value) {
                this.methodology = value;
            }

            /**
             * Gets the value of the inference property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getInference() {
                return inference;
            }

            /**
             * Sets the value of the inference property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setInference(TRevisionEvaluation value) {
                this.inference = value;
            }

            /**
             * Gets the value of the readability property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getReadability() {
                return readability;
            }

            /**
             * Sets the value of the readability property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setReadability(TRevisionEvaluation value) {
                this.readability = value;
            }

        }

    }

}
