//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 10:04:20 PM CET 
//


package ftn.xscience.model.publication;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_xscience_com.data.publication package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TStyleBold_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Bold");
    private final static QName _TStyleUnderline_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Underline");
    private final static QName _TStyleItalic_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Italic");
    private final static QName _TParagraphContentFigure_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Figure");
    private final static QName _TParagraphContentHyperlink_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Hyperlink");
    private final static QName _TParagraphContentStyle_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Style");
    private final static QName _TParagraphContentList_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "List");
    private final static QName _TParagraphContentQuote_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Quote");
    private final static QName _TParagraphContentTable_QNAME = new QName("https://www.xscience.com/data/publication.xsd", "Table");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_xscience_com.data.publication
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Publication }
     * 
     */
    public Publication createPublication() {
        return new Publication();
    }

    /**
     * Create an instance of {@link TTable }
     * 
     */
    public TTable createTTable() {
        return new TTable();
    }

    /**
     * Create an instance of {@link Publication.Content }
     * 
     */
    public Publication.Content createPublicationContent() {
        return new Publication.Content();
    }

    /**
     * Create an instance of {@link Publication.MetaData }
     * 
     */
    public Publication.MetaData createPublicationMetaData() {
        return new Publication.MetaData();
    }

    /**
     * Create an instance of {@link Publication.MetaData.Keywords }
     * 
     */
    public Publication.MetaData.Keywords createPublicationMetaDataKeywords() {
        return new Publication.MetaData.Keywords();
    }

    /**
     * Create an instance of {@link Publication.Title }
     * 
     */
    public Publication.Title createPublicationTitle() {
        return new Publication.Title();
    }

    /**
     * Create an instance of {@link Publication.Author }
     * 
     */
    public Publication.Author createPublicationAuthor() {
        return new Publication.Author();
    }

    /**
     * Create an instance of {@link Publication.Abstract }
     * 
     */
    public Publication.Abstract createPublicationAbstract() {
        return new Publication.Abstract();
    }

    /**
     * Create an instance of {@link Publication.References }
     * 
     */
    public Publication.References createPublicationReferences() {
        return new Publication.References();
    }

    /**
     * Create an instance of {@link Publication.CorrespondingAuthor }
     * 
     */
    public Publication.CorrespondingAuthor createPublicationCorrespondingAuthor() {
        return new Publication.CorrespondingAuthor();
    }

    /**
     * Create an instance of {@link TitleType }
     * 
     */
    public TitleType createTitleType() {
        return new TitleType();
    }

    /**
     * Create an instance of {@link HyperlinkType }
     * 
     */
    public HyperlinkType createHyperlinkType() {
        return new HyperlinkType();
    }

    /**
     * Create an instance of {@link TParagraphContent }
     * 
     */
    public TParagraphContent createTParagraphContent() {
        return new TParagraphContent();
    }

    /**
     * Create an instance of {@link TStyle }
     * 
     */
    public TStyle createTStyle() {
        return new TStyle();
    }

    /**
     * Create an instance of {@link https.www_xscience_com.data.publication.PaperType }
     * 
     */
    public ftn.xscience.model.publication.PaperType createPaperType() {
        return new ftn.xscience.model.publication.PaperType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link TAffiliation }
     * 
     */
    public TAffiliation createTAffiliation() {
        return new TAffiliation();
    }

    /**
     * Create an instance of {@link TQuote }
     * 
     */
    public TQuote createTQuote() {
        return new TQuote();
    }

    /**
     * Create an instance of {@link TFigure }
     * 
     */
    public TFigure createTFigure() {
        return new TFigure();
    }

    /**
     * Create an instance of {@link TReference }
     * 
     */
    public TReference createTReference() {
        return new TReference();
    }

    /**
     * Create an instance of {@link TList }
     * 
     */
    public TList createTList() {
        return new TList();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link TAuthorInformation }
     * 
     */
    public TAuthorInformation createTAuthorInformation() {
        return new TAuthorInformation();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link TName }
     * 
     */
    public TName createTName() {
        return new TName();
    }

    /**
     * Create an instance of {@link TTable.Row }
     * 
     */
    public TTable.Row createTTableRow() {
        return new TTable.Row();
    }

    /**
     * Create an instance of {@link Publication.Content.Paragraph }
     * 
     */
    public Publication.Content.Paragraph createPublicationContentParagraph() {
        return new Publication.Content.Paragraph();
    }

    /**
     * Create an instance of {@link Publication.MetaData.FieldOfStudy }
     * 
     */
    public Publication.MetaData.FieldOfStudy createPublicationMetaDataFieldOfStudy() {
        return new Publication.MetaData.FieldOfStudy();
    }

    /**
     * Create an instance of {@link Publication.MetaData.PaperType }
     * 
     */
    public Publication.MetaData.PaperType createPublicationMetaDataPaperType() {
        return new Publication.MetaData.PaperType();
    }

    /**
     * Create an instance of {@link Publication.MetaData.Recieved }
     * 
     */
    public Publication.MetaData.Recieved createPublicationMetaDataRecieved() {
        return new Publication.MetaData.Recieved();
    }

    /**
     * Create an instance of {@link Publication.MetaData.Revised }
     * 
     */
    public Publication.MetaData.Revised createPublicationMetaDataRevised() {
        return new Publication.MetaData.Revised();
    }

    /**
     * Create an instance of {@link Publication.MetaData.Accepted }
     * 
     */
    public Publication.MetaData.Accepted createPublicationMetaDataAccepted() {
        return new Publication.MetaData.Accepted();
    }

    /**
     * Create an instance of {@link Publication.MetaData.Status }
     * 
     */
    public Publication.MetaData.Status createPublicationMetaDataStatus() {
        return new Publication.MetaData.Status();
    }

    /**
     * Create an instance of {@link Publication.MetaData.Keywords.Keyword }
     * 
     */
    public Publication.MetaData.Keywords.Keyword createPublicationMetaDataKeywordsKeyword() {
        return new Publication.MetaData.Keywords.Keyword();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Bold", scope = TStyle.class)
    public JAXBElement<TStyle> createTStyleBold(TStyle value) {
        return new JAXBElement<TStyle>(_TStyleBold_QNAME, TStyle.class, TStyle.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Underline", scope = TStyle.class)
    public JAXBElement<TStyle> createTStyleUnderline(TStyle value) {
        return new JAXBElement<TStyle>(_TStyleUnderline_QNAME, TStyle.class, TStyle.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Italic", scope = TStyle.class)
    public JAXBElement<TStyle> createTStyleItalic(TStyle value) {
        return new JAXBElement<TStyle>(_TStyleItalic_QNAME, TStyle.class, TStyle.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFigure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Figure", scope = TParagraphContent.class)
    public JAXBElement<TFigure> createTParagraphContentFigure(TFigure value) {
        return new JAXBElement<TFigure>(_TParagraphContentFigure_QNAME, TFigure.class, TParagraphContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HyperlinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Hyperlink", scope = TParagraphContent.class)
    public JAXBElement<HyperlinkType> createTParagraphContentHyperlink(HyperlinkType value) {
        return new JAXBElement<HyperlinkType>(_TParagraphContentHyperlink_QNAME, HyperlinkType.class, TParagraphContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Style", scope = TParagraphContent.class)
    public JAXBElement<TStyle> createTParagraphContentStyle(TStyle value) {
        return new JAXBElement<TStyle>(_TParagraphContentStyle_QNAME, TStyle.class, TParagraphContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "List", scope = TParagraphContent.class)
    public JAXBElement<TList> createTParagraphContentList(TList value) {
        return new JAXBElement<TList>(_TParagraphContentList_QNAME, TList.class, TParagraphContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQuote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Quote", scope = TParagraphContent.class)
    public JAXBElement<TQuote> createTParagraphContentQuote(TQuote value) {
        return new JAXBElement<TQuote>(_TParagraphContentQuote_QNAME, TQuote.class, TParagraphContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.xscience.com/data/publication.xsd", name = "Table", scope = TParagraphContent.class)
    public JAXBElement<TTable> createTParagraphContentTable(TTable value) {
        return new JAXBElement<TTable>(_TParagraphContentTable_QNAME, TTable.class, TParagraphContent.class, value);
    }

}
