//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 10:04:20 PM CET 
//


package ftn.xscience.model.publication;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FieldOfStudy">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:fieldOfStudy" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PaperType">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>paperType">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Recieved">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:recieved" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Revised">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:revised" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Accepted">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:accepted" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Status">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>statusType">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Keywords">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Keyword" maxOccurs="10">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
 *                                   &lt;/restriction>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Title">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>titleType">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Author" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{https://www.xscience.com/data/publication.xsd}TAuthorInformation">
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:authoredBy" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Abstract">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="Content" type="{https://www.xscience.com/data/publication.xsd}TStyle"/>
 *                   &lt;element name="Quote" type="{https://www.xscience.com/data/publication.xsd}TQuote"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Content">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Paragraph" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ParagraphTitle">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ParagraphContent" type="{https://www.xscience.com/data/publication.xsd}TParagraphContent"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="level" default="1">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                                 &lt;maxInclusive value="5"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="References">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Reference" type="{https://www.xscience.com/data/publication.xsd}TReference" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Corresponding_author">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{https://www.xscience.com/data/publication.xsd}TAuthorInformation">
 *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:mentoredBy" />
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}language" default="en-US" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaData",
    "title",
    "author",
    "_abstract",
    "content",
    "references",
    "correspondingAuthor"
})
@XmlRootElement(name = "Publication")
public class Publication {

    @XmlElement(name = "MetaData", required = true)
    protected Publication.MetaData metaData;
    @XmlElement(name = "Title", required = true)
    protected Publication.Title title;
    @XmlElement(name = "Author", required = true)
    protected List<Publication.Author> author;
    @XmlElement(name = "Abstract", required = true)
    protected Publication.Abstract _abstract;
    @XmlElement(name = "Content", required = true)
    protected Publication.Content content;
    @XmlElement(name = "References", required = true)
    protected Publication.References references;
    @XmlElement(name = "Corresponding_author", required = true)
    protected Publication.CorrespondingAuthor correspondingAuthor;
    @XmlAttribute(name = "language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String language;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "version")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger version;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "vocab")
    @XmlSchemaType(name = "anySimpleType")
    protected String vocab;

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link Publication.MetaData }
     *     
     */
    public Publication.MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publication.MetaData }
     *     
     */
    public void setMetaData(Publication.MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Publication.Title }
     *     
     */
    public Publication.Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publication.Title }
     *     
     */
    public void setTitle(Publication.Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the author property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Publication.Author }
     * 
     * 
     */
    public List<Publication.Author> getAuthor() {
        if (author == null) {
            author = new ArrayList<Publication.Author>();
        }
        return this.author;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Publication.Abstract }
     *     
     */
    public Publication.Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publication.Abstract }
     *     
     */
    public void setAbstract(Publication.Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Publication.Content }
     *     
     */
    public Publication.Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publication.Content }
     *     
     */
    public void setContent(Publication.Content value) {
        this.content = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link Publication.References }
     *     
     */
    public Publication.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publication.References }
     *     
     */
    public void setReferences(Publication.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the correspondingAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link Publication.CorrespondingAuthor }
     *     
     */
    public Publication.CorrespondingAuthor getCorrespondingAuthor() {
        return correspondingAuthor;
    }

    /**
     * Sets the value of the correspondingAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publication.CorrespondingAuthor }
     *     
     */
    public void setCorrespondingAuthor(Publication.CorrespondingAuthor value) {
        this.correspondingAuthor = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        if (language == null) {
            return "en-US";
        } else {
            return language;
        }
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the vocab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocab() {
        return vocab;
    }

    /**
     * Sets the value of the vocab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocab(String value) {
        this.vocab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="Content" type="{https://www.xscience.com/data/publication.xsd}TStyle"/>
     *         &lt;element name="Quote" type="{https://www.xscience.com/data/publication.xsd}TQuote"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentOrQuote"
    })
    public static class Abstract {

        @XmlElements({
            @XmlElement(name = "Content", type = TStyle.class),
            @XmlElement(name = "Quote", type = TQuote.class)
        })
        protected List<Object> contentOrQuote;

        /**
         * Gets the value of the contentOrQuote property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentOrQuote property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentOrQuote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TStyle }
         * {@link TQuote }
         * 
         * 
         */
        public List<Object> getContentOrQuote() {
            if (contentOrQuote == null) {
                contentOrQuote = new ArrayList<Object>();
            }
            return this.contentOrQuote;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{https://www.xscience.com/data/publication.xsd}TAuthorInformation">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:authoredBy" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Author
        extends TAuthorInformation
    {

        @XmlAttribute(name = "href")
        protected String href;
        @XmlAttribute(name = "rel")
        protected String rel;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the rel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRel() {
            if (rel == null) {
                return "pred:authoredBy";
            } else {
                return rel;
            }
        }

        /**
         * Sets the value of the rel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRel(String value) {
            this.rel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Paragraph" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ParagraphTitle">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ParagraphContent" type="{https://www.xscience.com/data/publication.xsd}TParagraphContent"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="level" default="1">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                       &lt;maxInclusive value="5"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paragraph"
    })
    public static class Content {

        @XmlElement(name = "Paragraph", required = true)
        protected List<Publication.Content.Paragraph> paragraph;

        /**
         * Gets the value of the paragraph property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paragraph property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParagraph().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Publication.Content.Paragraph }
         * 
         * 
         */
        public List<Publication.Content.Paragraph> getParagraph() {
            if (paragraph == null) {
                paragraph = new ArrayList<Publication.Content.Paragraph>();
            }
            return this.paragraph;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ParagraphTitle">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ParagraphContent" type="{https://www.xscience.com/data/publication.xsd}TParagraphContent"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="level" default="1">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
         *             &lt;maxInclusive value="5"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "paragraphTitle",
            "paragraphContent"
        })
        public static class Paragraph {

            @XmlElement(name = "ParagraphTitle", required = true)
            protected String paragraphTitle;
            @XmlElement(name = "ParagraphContent", required = true)
            protected TParagraphContent paragraphContent;
            @XmlAttribute(name = "id")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "level")
            protected Integer level;

            /**
             * Gets the value of the paragraphTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParagraphTitle() {
                return paragraphTitle;
            }

            /**
             * Sets the value of the paragraphTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParagraphTitle(String value) {
                this.paragraphTitle = value;
            }

            /**
             * Gets the value of the paragraphContent property.
             * 
             * @return
             *     possible object is
             *     {@link TParagraphContent }
             *     
             */
            public TParagraphContent getParagraphContent() {
                return paragraphContent;
            }

            /**
             * Sets the value of the paragraphContent property.
             * 
             * @param value
             *     allowed object is
             *     {@link TParagraphContent }
             *     
             */
            public void setParagraphContent(TParagraphContent value) {
                this.paragraphContent = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the level property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getLevel() {
                if (level == null) {
                    return  1;
                } else {
                    return level;
                }
            }

            /**
             * Sets the value of the level property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLevel(Integer value) {
                this.level = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{https://www.xscience.com/data/publication.xsd}TAuthorInformation">
     *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:mentoredBy" />
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CorrespondingAuthor
        extends TAuthorInformation
    {

        @XmlAttribute(name = "rel")
        protected String rel;
        @XmlAttribute(name = "href")
        protected String href;

        /**
         * Gets the value of the rel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRel() {
            if (rel == null) {
                return "pred:mentoredBy";
            } else {
                return rel;
            }
        }

        /**
         * Sets the value of the rel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRel(String value) {
            this.rel = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FieldOfStudy">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:fieldOfStudy" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PaperType">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>paperType">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Recieved">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:recieved" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Revised">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:revised" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Accepted">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:accepted" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Status">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>statusType">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Keywords">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Keyword" maxOccurs="10">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
     *                         &lt;/restriction>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldOfStudy",
        "paperType",
        "recieved",
        "revised",
        "accepted",
        "status",
        "keywords"
    })
    public static class MetaData {

        @XmlElement(name = "FieldOfStudy", required = true)
        protected Publication.MetaData.FieldOfStudy fieldOfStudy;
        @XmlElement(name = "PaperType", required = true, defaultValue = "RESEARCH_PAPER")
        protected Publication.MetaData.PaperType paperType;
        @XmlElement(name = "Recieved", required = true)
        protected Publication.MetaData.Recieved recieved;
        @XmlElement(name = "Revised", required = true)
        protected Publication.MetaData.Revised revised;
        @XmlElement(name = "Accepted", required = true)
        protected Publication.MetaData.Accepted accepted;
        @XmlElement(name = "Status", required = true)
        protected Publication.MetaData.Status status;
        @XmlElement(name = "Keywords", required = true)
        protected Publication.MetaData.Keywords keywords;

        /**
         * Gets the value of the fieldOfStudy property.
         * 
         * @return
         *     possible object is
         *     {@link Publication.MetaData.FieldOfStudy }
         *     
         */
        public Publication.MetaData.FieldOfStudy getFieldOfStudy() {
            return fieldOfStudy;
        }

        /**
         * Sets the value of the fieldOfStudy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Publication.MetaData.FieldOfStudy }
         *     
         */
        public void setFieldOfStudy(Publication.MetaData.FieldOfStudy value) {
            this.fieldOfStudy = value;
        }

        /**
         * Gets the value of the paperType property.
         * 
         * @return
         *     possible object is
         *     {@link Publication.MetaData.PaperType }
         *     
         */
        public Publication.MetaData.PaperType getPaperType() {
            return paperType;
        }

        /**
         * Sets the value of the paperType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Publication.MetaData.PaperType }
         *     
         */
        public void setPaperType(Publication.MetaData.PaperType value) {
            this.paperType = value;
        }

        /**
         * Gets the value of the recieved property.
         * 
         * @return
         *     possible object is
         *     {@link Publication.MetaData.Recieved }
         *     
         */
        public Publication.MetaData.Recieved getRecieved() {
            return recieved;
        }

        /**
         * Sets the value of the recieved property.
         * 
         * @param value
         *     allowed object is
         *     {@link Publication.MetaData.Recieved }
         *     
         */
        public void setRecieved(Publication.MetaData.Recieved value) {
            this.recieved = value;
        }

        /**
         * Gets the value of the revised property.
         * 
         * @return
         *     possible object is
         *     {@link Publication.MetaData.Revised }
         *     
         */
        public Publication.MetaData.Revised getRevised() {
            return revised;
        }

        /**
         * Sets the value of the revised property.
         * 
         * @param value
         *     allowed object is
         *     {@link Publication.MetaData.Revised }
         *     
         */
        public void setRevised(Publication.MetaData.Revised value) {
            this.revised = value;
        }

        /**
         * Gets the value of the accepted property.
         * 
         * @return
         *     possible object is
         *     {@link Publication.MetaData.Accepted }
         *     
         */
        public Publication.MetaData.Accepted getAccepted() {
            return accepted;
        }

        /**
         * Sets the value of the accepted property.
         * 
         * @param value
         *     allowed object is
         *     {@link Publication.MetaData.Accepted }
         *     
         */
        public void setAccepted(Publication.MetaData.Accepted value) {
            this.accepted = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link Publication.MetaData.Status }
         *     
         */
        public Publication.MetaData.Status getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link Publication.MetaData.Status }
         *     
         */
        public void setStatus(Publication.MetaData.Status value) {
            this.status = value;
        }

        /**
         * Gets the value of the keywords property.
         * 
         * @return
         *     possible object is
         *     {@link Publication.MetaData.Keywords }
         *     
         */
        public Publication.MetaData.Keywords getKeywords() {
            return keywords;
        }

        /**
         * Sets the value of the keywords property.
         * 
         * @param value
         *     allowed object is
         *     {@link Publication.MetaData.Keywords }
         *     
         */
        public void setKeywords(Publication.MetaData.Keywords value) {
            this.keywords = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:accepted" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Accepted
            extends DateType
        {

            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:accepted";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:fieldOfStudy" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class FieldOfStudy {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:fieldOfStudy";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Keyword" maxOccurs="10">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
         *               &lt;/restriction>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "keyword"
        })
        public static class Keywords {

            @XmlElement(name = "Keyword", required = true)
            protected List<Publication.MetaData.Keywords.Keyword> keyword;

            /**
             * Gets the value of the keyword property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the keyword property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKeyword().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Publication.MetaData.Keywords.Keyword }
             * 
             * 
             */
            public List<Publication.MetaData.Keywords.Keyword> getKeyword() {
                if (keyword == null) {
                    keyword = new ArrayList<Publication.MetaData.Keywords.Keyword>();
                }
                return this.keyword;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
             *     &lt;/restriction>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Keyword
                extends KeywordType
            {


            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>paperType">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PaperType
            extends ftn.xscience.model.publication.PaperType
        {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:recieved" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Recieved
            extends DateType
        {

            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:recieved";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;https://www.xscience.com/data/publication.xsd>dateType">
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:revised" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Revised
            extends DateType
        {

            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:revised";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>statusType">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Status
            extends StatusType
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Reference" type="{https://www.xscience.com/data/publication.xsd}TReference" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reference"
    })
    public static class References {

        @XmlElement(name = "Reference", required = true)
        protected List<TReference> reference;

        /**
         * Gets the value of the reference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TReference }
         * 
         * 
         */
        public List<TReference> getReference() {
            if (reference == null) {
                reference = new ArrayList<TReference>();
            }
            return this.reference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>titleType">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Title
        extends TitleType
    {


    }

}
