//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 09:21:36 PM CET 
//


package ftn.xscience.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Content"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="evaluation"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="originality" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
 *                             &lt;element name="adequate_literature" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
 *                             &lt;element name="methodology" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
 *                             &lt;element name="inference" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
 *                             &lt;element name="readability" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="recommendations_for_editor"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="ACCEPT"/&gt;
 *                         &lt;enumeration value="MINOR REVISION"/&gt;
 *                         &lt;enumeration value="MAJOR REVISION"/&gt;
 *                         &lt;enumeration value="REJECT"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="comment_for_editor" type="{https://www.xscience.com/data/review.xsd}TCommentForEditor" minOccurs="0"/&gt;
 *                   &lt;element name="comment_for_author" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="edit_suggestion" type="{https://www.xscience.com/data/review.xsd}TEditSuggestion" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Review", namespace = "https://www.xscience.com/data/review.xsd")
public class Review {

    @XmlElement(name = "Content", namespace = "https://www.xscience.com/data/review.xsd", required = true)
    protected Review.Content content;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Content }
     *     
     */
    public Review.Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Content }
     *     
     */
    public void setContent(Review.Content value) {
        this.content = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="evaluation"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="originality" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
     *                   &lt;element name="adequate_literature" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
     *                   &lt;element name="methodology" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
     *                   &lt;element name="inference" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
     *                   &lt;element name="readability" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="recommendations_for_editor"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="ACCEPT"/&gt;
     *               &lt;enumeration value="MINOR REVISION"/&gt;
     *               &lt;enumeration value="MAJOR REVISION"/&gt;
     *               &lt;enumeration value="REJECT"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="comment_for_editor" type="{https://www.xscience.com/data/review.xsd}TCommentForEditor" minOccurs="0"/&gt;
     *         &lt;element name="comment_for_author" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="edit_suggestion" type="{https://www.xscience.com/data/review.xsd}TEditSuggestion" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "evaluation",
        "recommendationsForEditor",
        "commentForEditor",
        "commentForAuthor"
    })
    public static class Content {

        @XmlElement(namespace = "https://www.xscience.com/data/review.xsd", required = true)
        protected Review.Content.Evaluation evaluation;
        @XmlElement(name = "recommendations_for_editor", namespace = "https://www.xscience.com/data/review.xsd", required = true)
        protected String recommendationsForEditor;
        @XmlElement(name = "comment_for_editor", namespace = "https://www.xscience.com/data/review.xsd")
        protected TCommentForEditor commentForEditor;
        @XmlElement(name = "comment_for_author", namespace = "https://www.xscience.com/data/review.xsd")
        protected Review.Content.CommentForAuthor commentForAuthor;

        /**
         * Gets the value of the evaluation property.
         * 
         * @return
         *     possible object is
         *     {@link Review.Content.Evaluation }
         *     
         */
        public Review.Content.Evaluation getEvaluation() {
            return evaluation;
        }

        /**
         * Sets the value of the evaluation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Review.Content.Evaluation }
         *     
         */
        public void setEvaluation(Review.Content.Evaluation value) {
            this.evaluation = value;
        }

        /**
         * Gets the value of the recommendationsForEditor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecommendationsForEditor() {
            return recommendationsForEditor;
        }

        /**
         * Sets the value of the recommendationsForEditor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecommendationsForEditor(String value) {
            this.recommendationsForEditor = value;
        }

        /**
         * Gets the value of the commentForEditor property.
         * 
         * @return
         *     possible object is
         *     {@link TCommentForEditor }
         *     
         */
        public TCommentForEditor getCommentForEditor() {
            return commentForEditor;
        }

        /**
         * Sets the value of the commentForEditor property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCommentForEditor }
         *     
         */
        public void setCommentForEditor(TCommentForEditor value) {
            this.commentForEditor = value;
        }

        /**
         * Gets the value of the commentForAuthor property.
         * 
         * @return
         *     possible object is
         *     {@link Review.Content.CommentForAuthor }
         *     
         */
        public Review.Content.CommentForAuthor getCommentForAuthor() {
            return commentForAuthor;
        }

        /**
         * Sets the value of the commentForAuthor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Review.Content.CommentForAuthor }
         *     
         */
        public void setCommentForAuthor(Review.Content.CommentForAuthor value) {
            this.commentForAuthor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="edit_suggestion" type="{https://www.xscience.com/data/review.xsd}TEditSuggestion" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "editSuggestion"
        })
        public static class CommentForAuthor {

            @XmlElement(name = "edit_suggestion", namespace = "https://www.xscience.com/data/review.xsd")
            protected List<TEditSuggestion> editSuggestion;

            /**
             * Gets the value of the editSuggestion property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the editSuggestion property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEditSuggestion().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TEditSuggestion }
             * 
             * 
             */
            public List<TEditSuggestion> getEditSuggestion() {
                if (editSuggestion == null) {
                    editSuggestion = new ArrayList<TEditSuggestion>();
                }
                return this.editSuggestion;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="originality" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
         *         &lt;element name="adequate_literature" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
         *         &lt;element name="methodology" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
         *         &lt;element name="inference" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
         *         &lt;element name="readability" type="{https://www.xscience.com/data/review.xsd}TRevisionEvaluation"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "originality",
            "adequateLiterature",
            "methodology",
            "inference",
            "readability"
        })
        public static class Evaluation {

            @XmlElement(namespace = "https://www.xscience.com/data/review.xsd", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation originality;
            @XmlElement(name = "adequate_literature", namespace = "https://www.xscience.com/data/review.xsd", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation adequateLiterature;
            @XmlElement(namespace = "https://www.xscience.com/data/review.xsd", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation methodology;
            @XmlElement(namespace = "https://www.xscience.com/data/review.xsd", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation inference;
            @XmlElement(namespace = "https://www.xscience.com/data/review.xsd", required = true)
            @XmlSchemaType(name = "string")
            protected TRevisionEvaluation readability;

            /**
             * Gets the value of the originality property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getOriginality() {
                return originality;
            }

            /**
             * Sets the value of the originality property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setOriginality(TRevisionEvaluation value) {
                this.originality = value;
            }

            /**
             * Gets the value of the adequateLiterature property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getAdequateLiterature() {
                return adequateLiterature;
            }

            /**
             * Sets the value of the adequateLiterature property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setAdequateLiterature(TRevisionEvaluation value) {
                this.adequateLiterature = value;
            }

            /**
             * Gets the value of the methodology property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getMethodology() {
                return methodology;
            }

            /**
             * Sets the value of the methodology property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setMethodology(TRevisionEvaluation value) {
                this.methodology = value;
            }

            /**
             * Gets the value of the inference property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getInference() {
                return inference;
            }

            /**
             * Sets the value of the inference property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setInference(TRevisionEvaluation value) {
                this.inference = value;
            }

            /**
             * Gets the value of the readability property.
             * 
             * @return
             *     possible object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public TRevisionEvaluation getReadability() {
                return readability;
            }

            /**
             * Sets the value of the readability property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRevisionEvaluation }
             *     
             */
            public void setReadability(TRevisionEvaluation value) {
                this.readability = value;
            }

        }

    }

}
