//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 09:21:36 PM CET 
//


package ftn.xscience.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TParagraphContent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TParagraphContent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="Quote" type="{https://www.xscience.com/data/publication.xsd}TQuote"/&gt;
 *         &lt;element name="Figure" type="{https://www.xscience.com/data/publication.xsd}TFigure"/&gt;
 *         &lt;element name="List" type="{https://www.xscience.com/data/publication.xsd}TList"/&gt;
 *         &lt;element name="Table" type="{https://www.xscience.com/data/publication.xsd}TTable"/&gt;
 *         &lt;element name="Style" type="{https://www.xscience.com/data/publication.xsd}TStyle"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TParagraphContent", propOrder = {
    "content"
})
public class TParagraphContent {

    @XmlElementRefs({
        @XmlElementRef(name = "Quote", namespace = "https://www.xscience.com/data/publication.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Figure", namespace = "https://www.xscience.com/data/publication.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "List", namespace = "https://www.xscience.com/data/publication.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Table", namespace = "https://www.xscience.com/data/publication.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Style", namespace = "https://www.xscience.com/data/publication.xsd", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TQuote }{@code >}
     * {@link JAXBElement }{@code <}{@link TFigure }{@code >}
     * {@link JAXBElement }{@code <}{@link TList }{@code >}
     * {@link JAXBElement }{@code <}{@link TTable }{@code >}
     * {@link JAXBElement }{@code <}{@link TStyle }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
