//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.18 at 08:19:05 PM CET 
//


package ftn.xscience.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TPublication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPublication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="field_of_study" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="paper_type">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>paperType">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="received" type="{https://www.xscience.com/data/publication.xsd}dateType"/>
 *                   &lt;element name="revisied" type="{https://www.xscience.com/data/publication.xsd}dateType"/>
 *                   &lt;element name="accepted" type="{https://www.xscience.com/data/publication.xsd}dateType"/>
 *                   &lt;element name="status">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>statusType">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="keywords">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="keyword" maxOccurs="10">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
 *                                   &lt;/restriction>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Title">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Author" type="{https://www.xscience.com/data/publication.xsd}TAuthor" maxOccurs="unbounded"/>
 *         &lt;element name="Abstract">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="content" type="{https://www.xscience.com/data/publication.xsd}TStyle"/>
 *                   &lt;element name="quote" type="{https://www.xscience.com/data/publication.xsd}TQuote"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Content">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Paragraph" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Paragraph_title">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Paragraph_content" type="{https://www.xscience.com/data/publication.xsd}TParagraphContent"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="level" default="1">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                                 &lt;maxInclusive value="5"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="References">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Reference" type="{https://www.xscience.com/data/publication.xsd}TReference" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Corresponding_author" type="{https://www.xscience.com/data/publication.xsd}TAuthor"/>
 *       &lt;/sequence>
 *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}language" default="en-US" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPublication", propOrder = {
    "metaData",
    "title",
    "author",
    "_abstract",
    "content",
    "references",
    "correspondingAuthor"
})
public class TPublication {

    @XmlElement(name = "MetaData", required = true)
    protected TPublication.MetaData metaData;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Author", required = true)
    protected List<TAuthor> author;
    @XmlElement(name = "Abstract", required = true)
    protected TPublication.Abstract _abstract;
    @XmlElement(name = "Content", required = true)
    protected TPublication.Content content;
    @XmlElement(name = "References", required = true)
    protected TPublication.References references;
    @XmlElement(name = "Corresponding_author", required = true)
    protected TAuthor correspondingAuthor;
    @XmlAttribute(name = "language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String language;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "vocab")
    @XmlSchemaType(name = "anySimpleType")
    protected String vocab;

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link TPublication.MetaData }
     *     
     */
    public TPublication.MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublication.MetaData }
     *     
     */
    public void setMetaData(TPublication.MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the author property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAuthor }
     * 
     * 
     */
    public List<TAuthor> getAuthor() {
        if (author == null) {
            author = new ArrayList<TAuthor>();
        }
        return this.author;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link TPublication.Abstract }
     *     
     */
    public TPublication.Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublication.Abstract }
     *     
     */
    public void setAbstract(TPublication.Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link TPublication.Content }
     *     
     */
    public TPublication.Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublication.Content }
     *     
     */
    public void setContent(TPublication.Content value) {
        this.content = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link TPublication.References }
     *     
     */
    public TPublication.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublication.References }
     *     
     */
    public void setReferences(TPublication.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the correspondingAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link TAuthor }
     *     
     */
    public TAuthor getCorrespondingAuthor() {
        return correspondingAuthor;
    }

    /**
     * Sets the value of the correspondingAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAuthor }
     *     
     */
    public void setCorrespondingAuthor(TAuthor value) {
        this.correspondingAuthor = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        if (language == null) {
            return "en-US";
        } else {
            return language;
        }
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the vocab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocab() {
        return vocab;
    }

    /**
     * Sets the value of the vocab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocab(String value) {
        this.vocab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="content" type="{https://www.xscience.com/data/publication.xsd}TStyle"/>
     *         &lt;element name="quote" type="{https://www.xscience.com/data/publication.xsd}TQuote"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentOrQuote"
    })
    public static class Abstract {

        @XmlElements({
            @XmlElement(name = "content", type = TStyle.class),
            @XmlElement(name = "quote", type = TQuote.class)
        })
        protected List<Object> contentOrQuote;

        /**
         * Gets the value of the contentOrQuote property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentOrQuote property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentOrQuote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TStyle }
         * {@link TQuote }
         * 
         * 
         */
        public List<Object> getContentOrQuote() {
            if (contentOrQuote == null) {
                contentOrQuote = new ArrayList<Object>();
            }
            return this.contentOrQuote;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Paragraph" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Paragraph_title">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Paragraph_content" type="{https://www.xscience.com/data/publication.xsd}TParagraphContent"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="level" default="1">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                       &lt;maxInclusive value="5"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paragraph"
    })
    public static class Content {

        @XmlElement(name = "Paragraph", required = true)
        protected List<TPublication.Content.Paragraph> paragraph;

        /**
         * Gets the value of the paragraph property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paragraph property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParagraph().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TPublication.Content.Paragraph }
         * 
         * 
         */
        public List<TPublication.Content.Paragraph> getParagraph() {
            if (paragraph == null) {
                paragraph = new ArrayList<TPublication.Content.Paragraph>();
            }
            return this.paragraph;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Paragraph_title">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Paragraph_content" type="{https://www.xscience.com/data/publication.xsd}TParagraphContent"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="level" default="1">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
         *             &lt;maxInclusive value="5"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "paragraphTitle",
            "paragraphContent"
        })
        public static class Paragraph {

            @XmlElement(name = "Paragraph_title", required = true)
            protected String paragraphTitle;
            @XmlElement(name = "Paragraph_content", required = true)
            protected TParagraphContent paragraphContent;
            @XmlAttribute(name = "id")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "level")
            protected Integer level;

            /**
             * Gets the value of the paragraphTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParagraphTitle() {
                return paragraphTitle;
            }

            /**
             * Sets the value of the paragraphTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParagraphTitle(String value) {
                this.paragraphTitle = value;
            }

            /**
             * Gets the value of the paragraphContent property.
             * 
             * @return
             *     possible object is
             *     {@link TParagraphContent }
             *     
             */
            public TParagraphContent getParagraphContent() {
                return paragraphContent;
            }

            /**
             * Sets the value of the paragraphContent property.
             * 
             * @param value
             *     allowed object is
             *     {@link TParagraphContent }
             *     
             */
            public void setParagraphContent(TParagraphContent value) {
                this.paragraphContent = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the level property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getLevel() {
                if (level == null) {
                    return  1;
                } else {
                    return level;
                }
            }

            /**
             * Sets the value of the level property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLevel(Integer value) {
                this.level = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="field_of_study" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="paper_type">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>paperType">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="received" type="{https://www.xscience.com/data/publication.xsd}dateType"/>
     *         &lt;element name="revisied" type="{https://www.xscience.com/data/publication.xsd}dateType"/>
     *         &lt;element name="accepted" type="{https://www.xscience.com/data/publication.xsd}dateType"/>
     *         &lt;element name="status">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>statusType">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="keywords">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="keyword" maxOccurs="10">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
     *                         &lt;/restriction>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldOfStudy",
        "paperType",
        "received",
        "revisied",
        "accepted",
        "status",
        "keywords"
    })
    public static class MetaData {

        @XmlElement(name = "field_of_study", required = true)
        protected String fieldOfStudy;
        @XmlElement(name = "paper_type", required = true, defaultValue = "RESEARCH_PAPER")
        protected TPublication.MetaData.PaperType paperType;
        @XmlElement(required = true)
        protected DateType received;
        @XmlElement(required = true)
        protected DateType revisied;
        @XmlElement(required = true)
        protected DateType accepted;
        @XmlElement(required = true)
        protected TPublication.MetaData.Status status;
        @XmlElement(required = true)
        protected TPublication.MetaData.Keywords keywords;

        /**
         * Gets the value of the fieldOfStudy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFieldOfStudy() {
            return fieldOfStudy;
        }

        /**
         * Sets the value of the fieldOfStudy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFieldOfStudy(String value) {
            this.fieldOfStudy = value;
        }

        /**
         * Gets the value of the paperType property.
         * 
         * @return
         *     possible object is
         *     {@link TPublication.MetaData.PaperType }
         *     
         */
        public TPublication.MetaData.PaperType getPaperType() {
            return paperType;
        }

        /**
         * Sets the value of the paperType property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPublication.MetaData.PaperType }
         *     
         */
        public void setPaperType(TPublication.MetaData.PaperType value) {
            this.paperType = value;
        }

        /**
         * Gets the value of the received property.
         * 
         * @return
         *     possible object is
         *     {@link DateType }
         *     
         */
        public DateType getReceived() {
            return received;
        }

        /**
         * Sets the value of the received property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateType }
         *     
         */
        public void setReceived(DateType value) {
            this.received = value;
        }

        /**
         * Gets the value of the revisied property.
         * 
         * @return
         *     possible object is
         *     {@link DateType }
         *     
         */
        public DateType getRevisied() {
            return revisied;
        }

        /**
         * Sets the value of the revisied property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateType }
         *     
         */
        public void setRevisied(DateType value) {
            this.revisied = value;
        }

        /**
         * Gets the value of the accepted property.
         * 
         * @return
         *     possible object is
         *     {@link DateType }
         *     
         */
        public DateType getAccepted() {
            return accepted;
        }

        /**
         * Sets the value of the accepted property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateType }
         *     
         */
        public void setAccepted(DateType value) {
            this.accepted = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link TPublication.MetaData.Status }
         *     
         */
        public TPublication.MetaData.Status getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPublication.MetaData.Status }
         *     
         */
        public void setStatus(TPublication.MetaData.Status value) {
            this.status = value;
        }

        /**
         * Gets the value of the keywords property.
         * 
         * @return
         *     possible object is
         *     {@link TPublication.MetaData.Keywords }
         *     
         */
        public TPublication.MetaData.Keywords getKeywords() {
            return keywords;
        }

        /**
         * Sets the value of the keywords property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPublication.MetaData.Keywords }
         *     
         */
        public void setKeywords(TPublication.MetaData.Keywords value) {
            this.keywords = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="keyword" maxOccurs="10">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
         *               &lt;/restriction>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "keyword"
        })
        public static class Keywords {

            @XmlElement(required = true)
            protected List<TPublication.MetaData.Keywords.Keyword> keyword;

            /**
             * Gets the value of the keyword property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the keyword property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKeyword().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TPublication.MetaData.Keywords.Keyword }
             * 
             * 
             */
            public List<TPublication.MetaData.Keywords.Keyword> getKeyword() {
                if (keyword == null) {
                    keyword = new ArrayList<TPublication.MetaData.Keywords.Keyword>();
                }
                return this.keyword;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>keywordType">
             *     &lt;/restriction>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Keyword
                extends KeywordType
            {


            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>paperType">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PaperType
            extends ftn.xscience.model.PaperType
        {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;https://www.xscience.com/data/publication.xsd>statusType">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Status
            extends StatusType
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Reference" type="{https://www.xscience.com/data/publication.xsd}TReference" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reference"
    })
    public static class References {

        @XmlElement(name = "Reference", required = true)
        protected List<TReference> reference;

        /**
         * Gets the value of the reference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TReference }
         * 
         * 
         */
        public List<TReference> getReference() {
            if (reference == null) {
                reference = new ArrayList<TReference>();
            }
            return this.reference;
        }

    }

}
