//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 09:21:36 PM CET 
//


package ftn.xscience.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRevisionEvaluation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRevisionEvaluation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="STRONGLY AGREE"/&gt;
 *     &lt;enumeration value="AGREE"/&gt;
 *     &lt;enumeration value="NEUTRAL"/&gt;
 *     &lt;enumeration value="DISAGREE"/&gt;
 *     &lt;enumeration value="STRONGLY DISAGREE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TRevisionEvaluation", namespace = "https://www.xscience.com/data/review.xsd")
@XmlEnum
public enum TRevisionEvaluation {

    @XmlEnumValue("STRONGLY AGREE")
    STRONGLY_AGREE("STRONGLY AGREE"),
    AGREE("AGREE"),
    NEUTRAL("NEUTRAL"),
    DISAGREE("DISAGREE"),
    @XmlEnumValue("STRONGLY DISAGREE")
    STRONGLY_DISAGREE("STRONGLY DISAGREE");
    private final String value;

    TRevisionEvaluation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRevisionEvaluation fromValue(String v) {
        for (TRevisionEvaluation c: TRevisionEvaluation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
